---
#  Fiducial values of the cosmological parameters.
#  For more information, check LSST DESC SRD paper
#  (https://arxiv.org/abs/1809.01669) or CosmoLike
#  https://github.com/CosmoLike/DESC_SRD.

#  Cosmological parameters fiducial values
#  used in the analysis. Note that the order
#  of the parameters is important. Consult
#  the auxiliary_parameters.yaml in this dir.
srd:
  values:
    Omega_m: 0.3156  # Matter density fraction (dark matter + baryonic).
    sigma_8: 0.831  # Variance of matter density perturbations at an 8 Mpc/h scale.
    n_s: 0.9645  # Primordial scalar perturbation spectral index.
    w_0: -1.  # First order term of dark energy equation.
    w_a: 0.  # Second order term of dark energy equation.
    Omega_b: 0.0491685  # Baryonic matter density fraction.
    h: 0.6727  # Hubble constant divided by 100 km/s/Mpc; dimensionless.
  #  Errors on the cosmo params.yaml used in the analysis (used as Gaussian priors)
  sigmas:
    omega_m: 0.15
    sigma_8: 0.2
    n_s: 0.1
    w_0: 0.5
    w_a: 1.3
    omega_b: 0.005
    h: 0.125

...
